var  mystery = ['https://www.youtube.com/watch?v=lM6hQj4eDtA', 'https://www.youtube.com/watch?v=BMEnQe6JQYQ', 'Lmao your gay', 'https://www.youtube.com/watch?v=koLPQRpEAVU&t', 'https://www.youtube.com/watch?v=oAQuUuxnsUg&t', 
'https://cdn.discordapp.com/attachments/285880764493725696/672638833132699658/videoplayback.mp4', 'https://cdn.discordapp.com/attachments/285880764493725696/640329048261656586/604499.webm', 
'https://cdn.discordapp.com/attachments/412552225332920343/624208255765315594/FBI.mp4', 'https://cdn.discordapp.com/attachments/412552225332920343/624200372004585492/Kim_jong_boom.png', 'https://media.discordapp.net/attachments/412552225332920343/614810304294944804/image0.jpg',
'http://www.mediafire.com/file/x15pt4buqn6d1oc/REAL+PURO.rar', 'https://cdn.discordapp.com/attachments/412552225332920343/590710487830888461/image0.gif', 'https://www.youtube.com/watch?v=W9gxFkOz2_4&t=', 
'https://www.youtube.com/watch?v=9hAXae0jTws', 'https://cdn.discordapp.com/attachments/412552225332920343/556427074840035348/image0.jpg', 'https://cdn.discordapp.com/attachments/441228195191193600/513948416108265482/1516200361.png', 
'Australia is not real. Its a hoax, made for us to believe that Britain moved over their criminals to someplace. In reality, all these criminals were loaded off the ships into the waters, drowning before they could see land ever again. Its a coverup for one of the greatest mass murders in history, made by one of the most prominent empires. Australia does not exist. All things you call "proof" are actually well-fabricated lies and documents made by the leading governments of the world. Your Australian friends? Theyre all actors and computer-generated personas, part of the plot to trick the world.If you think youve ever been to Australia, youre terribly wrong. The plane pilots are all in on this, and have in all actuality only flown you to islands close nearby – or in some cases, parts of South America, where they have cleared space and hired actors to act out as real Australians. Australia is one of the biggest hoaxes ever created, and you have all been tricked. Join the movement today, and make it known that they have been deceived. Make it known, that this has all just been a cover-up. The things these "Australian" says to be doing, all these swear words and actions based on alcoholism, MDMA and bad decisions, are all ways to distract you from the ugly truth that is one of the greatest genocides in history. 162,000 people were said to have been transported to this imaginary land during a mere 80 years, and they are all long dead by now. They never reached that promised land. Tell the truth. Stand up for what is right. Make sure to spread the world – Australia is not real. Its a codeword for the cold-blooded murder of more than a hundred thousand people, and it is not okay. We will not accept this.Stand up for the ones who died. Let it be known, that Australia does not exist.', 
'What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.', 
'Rawr x3 nuzzles how are you pounces on you youre so warm o3o notices you have a bulge o: someones happy :wink: nuzzles your necky wecky~ murr~ hehehe rubbies your bulgy wolgy youre so big :oooo rubbies more on your bulgy wolgy it doesnt stop growing ·///· kisses you and lickies your necky daddy likies (; nuzzles wuzzles I hope daddy really likes $: wiggles butt and squirms I want to see your big daddy meat~ wiggles butt I have a little itch o3o wags tail can you please get my itch~ puts paws on your chest nyea~ its a seven inch itch rubs your chest can you help me pwease squirms pwetty pwease sad face I need to be punished runs paws down your chest and bites lip like I need to be punished really good~ paws on your bulge as I lick my lips Im getting thirsty. I can go for some milk unbuttons your pants as my eyes glow you smell so musky :v licks shaft mmmm~ so musky drools all over your cock your daddy meat I like fondles Mr. Fuzzy Balls hehe puts snout on balls and inhales deeply oh god im so hard~ licks balls punish me daddy~ nyea~ squirms more and wiggles butt I love your musky goodness bites lip please punish me licks lips nyea~ suckles on your tip so good licks pre of your cock salty goodness~ eyes role back and goes balls deep mmmm~ moans and suckles', 
'https://www.worldsdumbestgame.com/?gdpr=1', 'Fuck you, you get nothing', 'https://www.polkadotgame.com/', 'Gay', 'No', 'Supise!', 'https://www.youtube.com/watch?v=eM8Z9e-WoFs', 'https://www.youtube.com/watch?v=PYX8iDqCDAY&t=884s', 
'https://www.youtube.com/watch?v=2q82bGtujFA', 'https://www.youtube.com/watch?v=bUa5hKHWvRk', 'https://www.youtube.com/watch?v=IOsvuEA2h4w', 'https://www.youtube.com/watch?v=KQXHdxGb328', 'https://www.youtube.com/watch?v=5WBWIKnr0Os', 'https://music.youtube.com/watch?v=qMCYw3lSYhQ&list=OLAK5uy_lGOIBBAIqImxNYOEiQ2h5HzGXkRYmFbdE',
'https://youtu.be/hPsORRvJYco', 'https://youtu.be/xacdv8VO2EE', 'Twotter', 'https://youtu.be/mML2fPec7xU']
const Discord = require ('discord.js');
module.exports = {
    name: 'mystery',
    description: "???",
    execute(Client, message, args, Discord){
        message.channel.send(mystery[Math.floor(Math.random() * mystery.length)])
    }
}